export type QuestionType = 'essay' | 'choice' | 'extract';

export type Choice = {
  label: string;
  text: string;
};

export type Question = {
  id: string;
  materialId: 'milo' | 'science';
  materialTitle: string;
  number: number;
  page: string;
  line: string;
  type: QuestionType;
  title: string;
  question: string;
  modelAnswer: string;
  maxChars: number | null;
  choices?: Choice[];
  correctChoice?: string;
  explanation?: string;
};

export const questions: Question[] = [
  {
    id: "milo-01",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 1,
    page: "24",
    line: "1",
    type: "extract",
    title: "問1",
    question: "「両腕を失っていなければならなかった」とあるが、ミロのヴィーナスが両腕を失ったことを、筆者はどのように表現しているか。本文中より九字で抜き出せ。",
    modelAnswer: "部分的な具象の放棄",
    maxChars: 9,
  },
  {
    id: "milo-02",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 2,
    page: "24",
    line: "2",
    type: "extract",
    title: "問2",
    question: "「ふしぎな思い」に相当する部分を、本文中より四〇字以内で二か所探して、それぞれ最初と最後の五字を抜き出せ。",
    modelAnswer: "彼女がこん～らなかった／かったのだ・美術作品の～をしている",
    maxChars: 40,
  },
  {
    id: "milo-03",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 3,
    page: "24",
    line: "3",
    type: "choice",
    title: "問3",
    question: "「あずかり知らぬ」の意味として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "エ",
    maxChars: null,
    choices: [
      { label: "ア", text: "意図と逆の" },
      { label: "イ", text: "希望に反した" },
      { label: "ウ", text: "受け取っていない" },
      { label: "エ", text: "関知しない" },
    ],
    correctChoice: "エ",
    explanation: "「あずかり知らぬ」は、ここでは「関知しない」「関係していない」という意味。",
  },
  {
    id: "milo-04",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 4,
    page: "24",
    line: "9",
    type: "essay",
    title: "問4",
    question: "次の箇所に用いられている表現技法を指摘してみよう。\n「彼女はその両腕を、自分の美しさのために、無意識的に隠してきたのであった。よりよく国境を渡って行くために、そしてまた、よりよく時代を超えて行くために。」",
    modelAnswer: "擬人法。ミロのヴィーナスの像は生命体ではないが、「隠し」たり、「国境を渡っ」たり「時代を超え」たりする主語となっている。倒置法。「よりよく～」以下の理由の部分を後ろに置いて、その部分を強調している。反復の技法。「～ために」という二つの目的を畳みかけるように置くことで、よりその部分を強調している。",
    maxChars: null,
  },
  {
    id: "milo-05",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 5,
    page: "24",
    line: "9",
    type: "essay",
    title: "問5",
    question: "「よりよく国境を渡って行くために、そしてまた、よりよく時代を超えて行くために。」はどういうことか。次の語句をすべて用いて説明せよ。\n\nミロのヴィーナス　美　普遍的　意図　時間　一人歩き　空間　制作者　自身　輝き",
    modelAnswer: "ミロのヴィーナスが制作者の意図や時間・空間を超えた普遍的な美の輝きをもって彼女自身で一人歩きを始めたこと。",
    maxChars: null,
  },
  {
    id: "milo-06",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 6,
    page: "24",
    line: "11",
    type: "essay",
    title: "問6",
    question: "「部分的な具象の放棄による、ある全体性への偶然の肉迫」の表す意味を、個々の語句の意味を具体的に明らかにしながら説明してみよう。",
    modelAnswer: "「部分的な具象」は大理石でできた両腕を指す。「放棄」は両腕を失うこと。「全体性」とは、あらゆる美への可能性を秘めた完璧なまでの芸術性。「偶然」は予期したものではないこと、「肉迫」は身近に迫ること。つまり、ミロのヴィーナスが両腕を失うことによって、あらゆる美への可能性を秘めた完璧なまでの芸術作品に一気に近づくことを意味する。",
    maxChars: null,
  },
  {
    id: "milo-07",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 7,
    page: "24",
    line: "11",
    type: "choice",
    title: "問7",
    question: "「普遍」とあるが、ここではどのようなことを指しているか。最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "ウ",
    maxChars: null,
    choices: [
      { label: "ア", text: "両腕が失われる前の、世界中の誰からも愛されていた完璧なミロのヴィーナス。" },
      { label: "イ", text: "両腕が失われる前の、作者の意図や時代性を明確にしていたミロのヴィーナス。" },
      { label: "ウ", text: "両腕が失われた後の、時代や場所に関係なく魅力を発揮するミロのヴィーナス。" },
      { label: "エ", text: "両腕が失われた後の、一部の美術愛好家に偏愛されているミロのヴィーナス。" },
    ],
    correctChoice: "ウ",
    explanation: "ここでは、両腕を失った後のミロのヴィーナスが、時代や場所を超えて魅力を発揮することを指す。",
  },
  {
    id: "milo-08",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 8,
    page: "24",
    line: "11",
    type: "choice",
    title: "問8",
    question: "「巧まざる」の意味として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "ア",
    maxChars: null,
    choices: [
      { label: "ア", text: "工夫をこらさない" },
      { label: "イ", text: "技術的に未熟な" },
      { label: "ウ", text: "技巧を目立たなくした" },
      { label: "エ", text: "十分とは言えない" },
    ],
    correctChoice: "ア",
    explanation: "「巧まざる」は、意図的に工夫をこらしたわけではない、という意味。",
  },
  {
    id: "milo-09",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 9,
    page: "26",
    line: "1",
    type: "essay",
    title: "問9",
    question: "「逆説」とあるが、ここではどういうことか。四〇字以内で書け。",
    modelAnswer: "ミロのヴィーナスが魅力的であるのは、両腕を失っているからこそだということ。",
    maxChars: 40,
  },
  {
    id: "milo-10",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 10,
    page: "26",
    line: "5",
    type: "essay",
    title: "問10",
    question: "「均整の魔」とは、どのようなことか。",
    modelAnswer: "人間では考えられないほどうまく、肉体的なバランスが取れていること。また、それによって、人々を魅了し飽きさせないこと。",
    maxChars: null,
  },
  {
    id: "milo-11",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 11,
    page: "26",
    line: "6",
    type: "essay",
    title: "問11",
    question: "「生命の多様な可能性の夢を深々とたたえている。」の表す意味を、個々の語句の意味を具体的に明らかにしながら説明してみよう。",
    modelAnswer: "生きているもののさまざまな可能性という夢を内側にいっぱいもっているということ。両腕の喪失によって「存在すべき無数の美しい腕への暗示」という心象的な表現がもたらされ、生命の多様な可能性が支えられていることを表す。",
    maxChars: null,
  },
  {
    id: "milo-12",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 12,
    page: "26",
    line: "6",
    type: "extract",
    title: "問12",
    question: "「生命の多様な可能性の夢」と同様の意味を筆者が言い換えて表現している二〇字以内の語句を、教科書24ページ1行目～26ページ12行目から一つ抜き出せ。",
    modelAnswer: "存在すべき無数の美しい腕への暗示",
    maxChars: 20,
  },
  {
    id: "milo-13",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 13,
    page: "26",
    line: "11",
    type: "essay",
    title: "問13",
    question: "「そこに具体的な二本の腕が復活することを、ひそかに恐れる」とあるが、なぜ「恐れる」のか。その理由を「腕」「暗示」という二つの語句を用いて七〇字以内で説明せよ。",
    modelAnswer: "二本の腕が与えられたら、現在のミロのヴィーナスが持っている、存在すべき無数の腕への暗示という、ふしぎに心象的な表現が失われるから。",
    maxChars: 70,
  },
  {
    id: "milo-14",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 14,
    page: "26",
    line: "14",
    type: "essay",
    title: "問14",
    question: "「したがって」は、どのような内容を受けているか。",
    modelAnswer: "両腕が失われていることによって、生命の多様な可能性の夢、存在すべき無数の美しい腕への暗示を与えてくれた、という感動の体験をしてしまったこと。",
    maxChars: null,
  },
  {
    id: "milo-15",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 15,
    page: "27",
    line: "3",
    type: "essay",
    title: "問15",
    question: "「表現における量の変化ではなくて、質の変化である」の表す意味を、個々の語句の意味を具体的に明らかにしながら説明してみよう。",
    modelAnswer: "「量の変化」とは、二本の腕の分だけ表現の量が増減するということ。「質の変化」とは、両腕の有無によって、「心象的な表現」か否か、「普遍」的表現か「特殊」な表現かといった差異が生じること。両腕が復元されたミロのヴィーナスと両腕のないままのそれとでは、表現の次元そのものが異なるという意味。",
    maxChars: null,
  },
  {
    id: "milo-16",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 16,
    page: "27",
    line: "3",
    type: "extract",
    title: "問16",
    question: "「表現における量の変化ではなくて、質の変化である」の「量の変化」とは、ここではどういうことをいっているのか。本文中の語句を用いて、二五字以内で答えよ。",
    modelAnswer: "ミロのヴィーナスの失われた両腕を復元させること",
    maxChars: 25,
  },
  {
    id: "milo-17",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 17,
    page: "27",
    line: "4",
    type: "extract",
    title: "問17",
    question: "「表現における量の変化ではなくて、質の変化である」の「質の変化」とは、ここではどういうことをいっているのか。本文中の語句を用いて、一五字以内で答えよ。",
    modelAnswer: "表現の次元が異なること",
    maxChars: 15,
  },
  {
    id: "milo-18",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 18,
    page: "27",
    line: "5",
    type: "essay",
    title: "問18",
    question: "「他の対象」に傍点がついているのはなぜか。",
    modelAnswer: "「両腕のないミロのヴィーナス＝対象」と、復元案にもとづき両腕をつけた状態のミロのヴィーナスとを明確に区別するため。",
    maxChars: null,
  },
  {
    id: "milo-19",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 19,
    page: "27",
    line: "6",
    type: "essay",
    title: "問19",
    question: "「おびただしい夢をはらんでいる無」の表す意味を、個々の語句の意味を具体的に明らかにしながら説明してみよう。",
    modelAnswer: "「おびただしい」は数量が非常に多いさま。「夢」とは「生命の多様な可能性の夢」を指す。「はらむ」は内部に含みもつの意。「無」とは両腕がないミロのヴィーナスのあり方を指す。つまり、両腕がないことで生命の多様な可能性の夢を深々とたたえ、存在すべき無数の美しい腕を暗示するミロのヴィーナスという意味。",
    maxChars: null,
  },
  {
    id: "milo-20",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 20,
    page: "27",
    line: "15",
    type: "essay",
    title: "問20",
    question: "「おそろしくむなしい気持ち」になるのはなぜか。",
    modelAnswer: "すぐれた復元案の「選ばれたどんなイメージも」、両腕が失われていること以上の美しさを生みだすことができないから。",
    maxChars: null,
  },
  {
    id: "milo-21",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 21,
    page: "28",
    line: "1",
    type: "choice",
    title: "問21",
    question: "「失われていること以上の美しさを生みだすことができないのである」の理由として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "ア",
    maxChars: null,
    choices: [
      { label: "ア", text: "両腕が復元されることによって、生命の変幻自在な輝きが限定、固定化されてしまうから。" },
      { label: "イ", text: "両腕がどんなに正確に復元されても、真の原形の美しさよりも勝るとは考えられないから。" },
      { label: "ウ", text: "両腕が失われていることによって、人々はかえって両腕そのものの美しさを認識するから。" },
      { label: "エ", text: "両腕が失われていることによって、人間の生活における両腕の重要さが再認識されるから。" },
    ],
    correctChoice: "ア",
    explanation: "両腕の復元によって、失われた腕が生んでいた多様な可能性や生命の輝きが、具体的な形に限定されてしまうため。",
  },
  {
    id: "milo-22",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 22,
    page: "28",
    line: "6",
    type: "essay",
    title: "問22",
    question: "「失われているものが、両腕以外の何ものかであってはならない」とあるが、筆者はその理由をどのように説明しているか。",
    modelAnswer: "「腕というもの」特に「手というもの」は、目や鼻や乳房と違って、人間存在において「世界との、他人との、あるいは自己との、千変万化する交渉の手段」であることを「根源的に暗示」するという「象徴的な意味」をもつからである、と筆者は説明している。",
    maxChars: null,
  },
  {
    id: "milo-23",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 23,
    page: "28",
    line: "15",
    type: "essay",
    title: "問23",
    question: "筆者は「手」というものが「最も根源的に暗示しているもの」は、「千変万化する交渉の手段」だと述べている。このようなことを示す、手を用いた具体的な行動や慣用句を挙げてみよう。",
    modelAnswer: "握手をする、手を振る、といった行動。",
    maxChars: null,
  },
  {
    id: "milo-24",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 24,
    page: "28",
    line: "15",
    type: "extract",
    title: "問24",
    question: "「それ」がさす内容を答えよ。",
    modelAnswer: "腕（手）",
    maxChars: null,
  },
  {
    id: "milo-25",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 25,
    page: "28",
    line: "15",
    type: "extract",
    title: "問25",
    question: "「実体と象徴のある程度の合致」の「実体と象徴」の「合致」として適当な具体例を一つ、本文中より抜き出せ。",
    modelAnswer: "恋人の手をはじめて握る幸福",
    maxChars: null,
  },
  {
    id: "milo-26",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 26,
    page: "28",
    line: "16",
    type: "extract",
    title: "問26",
    question: "「それ」とは、何を指すか。",
    modelAnswer: "手というもの",
    maxChars: null,
  },
  {
    id: "milo-27",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 27,
    page: "28",
    line: "16",
    type: "essay",
    title: "問27",
    question: "「それ」がさす内容を答えよ。",
    modelAnswer: "手が最も深く、最も根源的に暗示しているもの、すなわち手というものが象徴、暗示するもの。",
    maxChars: null,
  },
  {
    id: "milo-28",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 28,
    page: "29",
    line: "1",
    type: "essay",
    title: "問28",
    question: "「千変万化」の意味を答えよ。",
    modelAnswer: "さまざまに変化すること。",
    maxChars: null,
  },
  {
    id: "milo-29",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 29,
    page: "29",
    line: "1",
    type: "essay",
    title: "問29",
    question: "「媒介」の意味を答えよ。",
    modelAnswer: "双方の間に立ってとりもつこと。",
    maxChars: null,
  },
  {
    id: "milo-30",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 30,
    page: "29",
    line: "4",
    type: "essay",
    title: "問30",
    question: "「厳粛」の意味を答えよ。",
    modelAnswer: "おごそかで慎み深いこと。",
    maxChars: null,
  },
  {
    id: "milo-31",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 31,
    page: "29",
    line: "6",
    type: "essay",
    title: "問31",
    question: "「ふしぎなアイロニー」とは、具体的にどういうことか。簡潔に説明せよ。",
    modelAnswer: "ミロのヴィーナスの両腕の欠落が、逆に可能なあらゆる手への夢を奏でること。",
    maxChars: null,
  },
  {
    id: "milo-32",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 32,
    page: "30",
    line: "-",
    type: "essay",
    title: "問32",
    question: "この文章は、一行空きによって三つの部分から成っている。それぞれの部分の要点を簡潔にまとめてみよう。",
    modelAnswer: "第一段落：ミロのヴィーナスは、両腕を失うことで、存在すべき無数の美しい腕を心象的に暗示するものとなり、普遍的な芸術性をたたえる魅力ある存在となった。\n第二段落：ミロのヴィーナスの両腕を復元する試みは、興ざめで、むなしいことに思われる。両腕のイメージを限定し、あらゆる美への可能性を奪うものはすべて、芸術の名において否認したい。\n第三段落：ミロのヴィーナスの失ったものが、ほかでもない両腕であった結果、逆に、可能なあらゆる手への夢を奏でるというアイロニーが成立する。",
    maxChars: null,
  },
  {
    id: "milo-33",
    materialId: "milo",
    materialTitle: "ミロのヴィーナス",
    number: 33,
    page: "30",
    line: "-",
    type: "essay",
    title: "問33",
    question: "何かが失われていたり、省略されていたりすることを肯定的にとらえている例を探し、それについて自分はどのように感じるか、話し合ってみよう。",
    modelAnswer: "俳句は、一七文字という短い形式に凝縮された言葉の芸術だが、一七文字の奥に隠れた句の世界を、読み手の想像力で広げていくところが魅力である。水墨画は、墨の濃淡だけで画面を構成する絵画だが、不要な要素を省略した「引き算」の美が見てとれる。",
    maxChars: null,
  },
  {
    id: "science-01",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 1,
    page: "72",
    line: "2",
    type: "extract",
    title: "問1",
    question: "「科学と生命は、実はとても似ている」とあるが、それを具体的に説明した一文をほかの段落から抜き出し、初めの五字を書け。",
    modelAnswer: "ある意味、",
    maxChars: null,
  },
  {
    id: "science-02",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 2,
    page: "72",
    line: "9",
    type: "essay",
    title: "問2",
    question: "「ノーベル賞を受賞した業績でも、後に間違いであることが判明した例もある。」とあるが、どのような例があるか、調べてみよう。",
    modelAnswer: "一九二六年にデンマークのヨハネス・フィビゲルが世界で初めて「がん」を人工的に引き起こすことに成功したという業績で、ノーベル生理学・医学賞を受賞したが、彼の死後、その研究が誤りであったことが明らかになった。",
    maxChars: null,
  },
  {
    id: "science-03",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 3,
    page: "72",
    line: "11",
    type: "choice",
    title: "問3",
    question: "「枚挙にいとまがない」の意味として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "エ",
    maxChars: null,
    choices: [
      { label: "ア", text: "批判されるべきでない" },
      { label: "イ", text: "認めるほどではない" },
      { label: "ウ", text: "仕方がないといえる" },
      { label: "エ", text: "数え切れないほど多い" },
    ],
    correctChoice: "エ",
    explanation: "「枚挙にいとまがない」は、一つ一つ数え上げる余裕がないほど多い、という意味。",
  },
  {
    id: "science-04",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 4,
    page: "73",
    line: "10",
    type: "essay",
    title: "問4",
    question: "「可塑性」とは、ここでは科学のどのような性質を指すか。",
    modelAnswer: "現実をよく説明する「適応度の高い仮説」が長い時間の中で批判に耐え生き残り、さらにその適応度を上げる修正仮説が提出されるサイクルが繰り返され、進化・成長していくという性質。",
    maxChars: null,
  },
  {
    id: "science-05",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 5,
    page: "73",
    line: "10",
    type: "choice",
    title: "問5",
    question: "「可塑性」の意味として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "イ",
    maxChars: null,
    choices: [
      { label: "ア", text: "過去をさかのぼる性質" },
      { label: "イ", text: "自在に変化し得る性質" },
      { label: "ウ", text: "現実をよく表す性質" },
      { label: "エ", text: "外圧にたえる性質" },
    ],
    correctChoice: "イ",
    explanation: "「可塑性」は、状況に応じて自在に変化し得る性質を指す。",
  },
  {
    id: "science-06",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 6,
    page: "73",
    line: "10",
    type: "essay",
    title: "問6",
    question: "「『可塑性』こそが科学の生命線である」とは、どういう意味か。次の文の空欄に適する語句を二〇字以内で書け。\n「可塑性」があるかないかが、（　　　）であるということ。",
    modelAnswer: "本当の科学かそうでないかの重要な境界線",
    maxChars: 20,
  },
  {
    id: "science-07",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 7,
    page: "73",
    line: "13",
    type: "essay",
    title: "問7",
    question: "「科学が教えるところは、すべて修正される可能性がある」とあるが、なぜか。「正しい」という言葉を使って四〇字以内で書け。",
    modelAnswer: "仮説を一〇〇％正しいと判定するプロセスが体系の中に用意されていないから。",
    maxChars: 40,
  },
  {
    id: "science-08",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 8,
    page: "74",
    line: "8",
    type: "choice",
    title: "問8",
    question: "「どんなに正しく見えることでも、それをさらに修正するための努力は、科学の世界では決して否定されない」とあるが、どういうことか。最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "エ",
    maxChars: null,
    choices: [
      { label: "ア", text: "現実に合わない仮説であっても、長い時間の中で批判を重ねていけば変化を生み出し、より適応することがあるということ。" },
      { label: "イ", text: "正しいと思われたニュートン力学が、アインシュタインの一般相対性理論によって否定され「不動の真理」はないと証明されたということ。" },
      { label: "ウ", text: "完全に正しい仮説は存在しないので、医学生物学論文のうちの多くが結果を再現できないという事実に落胆するべきではないということ。" },
      { label: "エ", text: "批判に耐えて生き残った「適応度の高い仮説」に対して、さらに適応度を上げる修正仮説を提出するサイクルが繰り返されるということ。" },
    ],
    correctChoice: "エ",
    explanation: "科学では、現実をよく説明する仮説であっても、さらに適応度を高める修正の努力が続けられるという意味。",
  },
  {
    id: "science-09",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 9,
    page: "74",
    line: "14",
    type: "essay",
    title: "問9",
    question: "「原理的に不完全な」とは、どのようなことか。",
    modelAnswer: "絶え間ない修正により、少しずつより真実の法則に近い仮説ができ上がってくるが、「不動の真理」であることを判定するプロセスが科学の体系には用意されていないということ。",
    maxChars: null,
  },
  {
    id: "science-10",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 10,
    page: "74",
    line: "14",
    type: "essay",
    title: "問10",
    question: "「『原理的に不完全な』科学的知見をどう捉えて、どのように使っていけばよいのだろうか。」とあるが、この問いに対する筆者の考えをまとめてみよう。",
    modelAnswer: "科学的知見の中には確度の高いものから低いものまで幅広く混在している。よりよい判断のため、それらの確度を正確に把握して峻別していくべきである。",
    maxChars: null,
  },
  {
    id: "science-11",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 11,
    page: "75",
    line: "9",
    type: "extract",
    title: "問11",
    question: "「根拠に基づく医療」とあるが、なぜこのような考え方が提唱されているのか。次の文の空欄に適する語句を、本文中から１は一五字、２は一一字で抜き出せ。\n科学的知見には（　　　１　　　）しているので、それらの（　　　２　　　）するため。",
    modelAnswer: "１＝確度が大きく異なったものが混在／２＝確からしさを正確に把握",
    maxChars: null,
  },
  {
    id: "science-12",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 12,
    page: "75",
    line: "14",
    type: "essay",
    title: "問12",
    question: "「意欲的な試み」とあるが、どのような点が「意欲的」なのか。「確度」という言葉を使って四〇字以内で書け。",
    modelAnswer: "非専門家でもデータの確度を判断できる基準を提供しようとしている点。",
    maxChars: 40,
  },
  {
    id: "science-13",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 13,
    page: "76",
    line: "5",
    type: "essay",
    title: "問13",
    question: "「現実的には相当に困難なことである」とあるがそれはなぜか。",
    modelAnswer: "非専門家でも理解しやすい情報は、すべての科学的な知見に対して公開されているわけではなく、情報の確度を画一的な視点で判断していく点にも問題がある。また、一つの問題に対して専門家でさえも意見が分かれることが非常に多いから。",
    maxChars: null,
  },
  {
    id: "science-14",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 14,
    page: "76",
    line: "9",
    type: "choice",
    title: "問14",
    question: "「権威主義」とあるが、どのようなものか。最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "ア",
    maxChars: null,
    choices: [
      { label: "ア", text: "専門家や実績のある立場の人が言うことは、その内容も正しいと信じてしまうこと。" },
      { label: "イ", text: "専門家や実績のある立場の人が言うことを、自分の意見の科学的根拠とすること。" },
      { label: "ウ", text: "専門家や実績のある立場の人が、科学的根拠もなく自分の意見を他人に押しつけること。" },
      { label: "エ", text: "専門家や実績のある立場の人に恐縮して、その意見に反論することができなくなること。" },
    ],
    correctChoice: "ア",
    explanation: "ここでの権威主義は、権威の高さと情報の確度を同一視して判断する態度を指す。",
  },
  {
    id: "science-15",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 15,
    page: "76",
    line: "12",
    type: "essay",
    title: "問15",
    question: "「現在の社会で『科学的な根拠』の確からしさを判断する方法として採用されているのは、この権威主義に基づいたものが主である」とあるが、「権威主義」に基づくことの利点と欠点を、本文全体をふまえて、説明してみよう。",
    modelAnswer: "利点は、確度の判定基準として分かりやすいこと。また、多くの専門家の厳しい審査に耐えてきた知見であり、そうでないものよりも強靭さを持つ傾向にあること。欠点は、分からないという不安から逃れたい心理に忍び込み、自らの理性で考えることから離れ、妄信的に安易に答えを受け入れるようになってしまうこと。また、科学を特別な位置に置き、高圧的・一方的に批判を抑えたり逸脱を認めなくなったりして、科学の性質であり生命である可塑性が蝕まれてしまうこと。",
    maxChars: null,
  },
  {
    id: "science-16",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 16,
    page: "77",
    line: "4",
    type: "essay",
    title: "問16",
    question: "「それで十分だという考え方」とあるが、なぜこのような考え方が生まれるのか。次の文の空欄に適する語句を、１は一〇字以内、２は二〇字以内で書け。\n科学的知見は（　　　１　　　）なので、（　　　２　　　）と考えるから。",
    modelAnswer: "１＝確度の判定が困難／２＝分かりやすい権威主義による判断でよい",
    maxChars: null,
  },
  {
    id: "science-17",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 17,
    page: "77",
    line: "13",
    type: "essay",
    title: "問17",
    question: "「そこ」とあるが、何を指しているか。二〇字以内で書け。",
    modelAnswer: "何かを信じて不安から逃れたいという心理。",
    maxChars: 20,
  },
  {
    id: "science-18",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 18,
    page: "78",
    line: "3",
    type: "essay",
    title: "問18",
    question: "「科学と社会の接点」とあるが、「科学」を「社会」の中で活用するためには、「専門家」と「非専門家」それぞれが、どのようにすることが必要か、本文をふまえて考えたことを話し合ってみよう。",
    modelAnswer: "専門家は、非専門家にもわかるように科学について説明することに努め、非専門家の意見にも耳を傾け、話し合いの場を設ける必要がある。また非専門家は、科学的な責任をすべて専門家に押し付けるのではなく、科学について積極的に理解しようと努め、前向きな意見を出す必要がある。",
    maxChars: null,
  },
  {
    id: "science-19",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 19,
    page: "78",
    line: "3",
    type: "extract",
    title: "問19",
    question: "「『科学と社会の接点』ではよく見られる現象」とあるが、どのようなものか。次の文の空欄１・２に適する語句をそれぞれ一五字以内で書け。\n非専門家が（　１　）と誤解することや、専門家が（　２　）こと。",
    modelAnswer: "１＝専門家の言うことなら正しい／２＝非専門家からの批判を封じ込める",
    maxChars: null,
  },
  {
    id: "science-20",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 20,
    page: "78",
    line: "7",
    type: "essay",
    title: "問20",
    question: "「科学の生命力」とは、どのようなことか。",
    modelAnswer: "科学の可塑性。科学の何物も不動の真理ではなく、それが修正され変わり得る性質のこと。",
    maxChars: null,
  },
  {
    id: "science-21",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 21,
    page: "78",
    line: "7",
    type: "essay",
    title: "問21",
    question: "「権威主義が『科学の生命力』を蝕む性質」とあるが、どのようなものか。それぞれ四〇字以内で二つ書け。",
    modelAnswer: "人々の信頼を失うことへの恐怖感から間違いを恐れ、考えが柔軟でなくなる。\n自分の信じる価値が崩壊するのを恐れ、権威の体系から逸脱するものを頑なに認めない。",
    maxChars: null,
  },
  {
    id: "science-22",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 22,
    page: "79",
    line: "6",
    type: "choice",
    title: "問22",
    question: "「妄信的」の意味として最も適当なものを、次のア～エから一つ選び、記号で答えよ。",
    modelAnswer: "イ",
    maxChars: null,
    choices: [
      { label: "ア", text: "押さえつけること。" },
      { label: "イ", text: "むやみに信じること。" },
      { label: "ウ", text: "ひどく迷うこと。" },
      { label: "エ", text: "こだわりが強いこと。" },
    ],
    correctChoice: "イ",
    explanation: "「妄信的」とは、十分に考えず、むやみに信じるさまをいう。",
  },
  {
    id: "science-23",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 23,
    page: "79",
    line: "7",
    type: "essay",
    title: "問23",
    question: "「まったく正反対」とあるが、どのような点で正反対なのか。",
    modelAnswer: "妄信的な権威主義が、権威に頼って安易に「正解」を得ようとするのに対して、科学を支える理性主義は、理性によって物事を先入観なくあるがままに見て、その意味や仕組みを考えようとする点。",
    maxChars: null,
  },
  {
    id: "science-24",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 24,
    page: "79",
    line: "7",
    type: "choice",
    title: "問24",
    question: "「まったく正反対」とあるが、なぜそう言えるのか。理由として最も適当なものを次のア～オから一つ選び、記号で答えよ。",
    modelAnswer: "ウ",
    maxChars: null,
    choices: [
      { label: "ア", text: "権威主義が人の心が持つ弱点に忍び込もうとするのに対して、理性主義では不安な心理を否定し理性で解決しようとするから。" },
      { label: "イ", text: "権威主義が専門家の意見を安易に受け入れるのに対して、理性主義では一〇〇％の真実にたどり着くまで仮説を認めないから。" },
      { label: "ウ", text: "権威主義が権威に頼って安易に「正解」を得るのに対して、理性主義では自分の理性で物事の意味や仕組みを考えるから。" },
      { label: "エ", text: "権威主義が自分の価値観に頑なにこだわるのに対して、理性主義では物事を客観的に捉えて専門家の意見を批判するから。" },
      { label: "オ", text: "権威主義が科学を特別なものとして位置付けるのに対して、理性主義では非専門家でも物事の意味や仕組みを考えるから。" },
    ],
    correctChoice: "ウ",
    explanation: "権威主義は権威に頼って安易に正解を得ようとするが、理性主義は自分の理性で意味や仕組みを考えるため、精神性が正反対である。",
  },
  {
    id: "science-25",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 25,
    page: "79",
    line: "12",
    type: "essay",
    title: "問25",
    question: "「科学には伽藍ではなくバザールが似合う。」とあるが、この表現は科学のどのような特徴を表しているか、説明してみよう。",
    modelAnswer: "一斉に権威を指向するのではなく、様々な個性を持った個々人の指向のまま、ランダムな方向を持ったものの集合体であるという科学の特徴を表している。",
    maxChars: null,
  },
  {
    id: "science-26",
    materialId: "science",
    materialTitle: "科学は生きている",
    number: 26,
    page: "81",
    line: "-",
    type: "essay",
    title: "問26",
    question: "筆者の述べる科学の特徴を、「科学と生命」「確度の問題」（72・1～74・11）の部分からまとめてみよう。",
    modelAnswer: "科学では、現実に合わない、現実を説明していない仮説が出されることが日常茶飯事であり、科学は修正されながら成長・進化していく。また絶え間ない修正でより真実に近い仮説ができ上がっていくが、「不動の真理」というものは存在せず、仮説がどれくらい確かなのかという確度の問題だけが存在する。",
    maxChars: null,
  },
];

export const materials = [
  { id: 'milo', title: 'ミロのヴィーナス' },
  { id: 'science', title: '科学は生きている' },
] as const;
